# Custom Language File for Launcher Customizer

[ejs.app]
title = "츄르네 낯선서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/BBibbabbro/Churoo_PersonaMC"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/w9Z4HufEhQ"

[ejs.settings]
sourceGithubLink = "https://github.com/BBibbabbro/Churoo_PersonaMC"
supportLink = "https://github.com/BBibbabbro/Churoo_PersonaMC/issues"

[ejs.welcome]
welcomeHeader = "츄르네 낯선서버에 오신 것을 환영합니다."
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
